# Generated by Django 5.2.10 on 2026-01-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'stock'], name='api_stock_timesta_8e3ae7_idx')],
            },
        ),
    ]
